[versions]
koin = "3.5.6"
activityCompose = "1.10.1"
coreKtx = "1.16.0"
android-gradle-plugin = "8.6.1"
kotlin = "2.0.20"
detektGradlePlugin = "1.18.1"
espressoCore = "3.6.1"
junit = "4.13.2"
junitVersion = "1.2.1"
lifecycleRuntimeKtx = "2.8.7"
material = "1.8.0"
material3Android = "1.3.2"
materialVersion = "1.12.0"
navigation-compose = "2.9.0"
ui = "1.8.0"
bugget-planner-base = "1.0.0"
budget-planner-onboarding = "1.0.0"
budget-planner-onboarding-navigation = "1.0.0"

[libraries]

# Koin
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-androix-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }

# Base
budget-planner-base = { module = "com.daniel:base", version.ref = "bugget-planner-base"}

# Products
budget-planner-onboarding = { module = "com.daniel.budgetplanner:onboarding", version.ref = "budget-planner-onboarding" }

# Products Navigations
budget-planner-onboarding-navigation = { module = "com.daniel.budgetplanner:onboarding-navigation", version.ref = "budget-planner-onboarding-navigation" }

# Compose
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose"}

# Android
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "android-gradle-plugin"}
detekt-gradle-plugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detektGradlePlugin" }

# Kotlin
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin"}

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-material = { module = "androidx.compose.material:material", version.ref = "material" }
androidx-material3-android = { module = "androidx.compose.material3:material3-android", version.ref = "material3Android" }
androidx-ui = { module = "androidx.compose.ui:ui", version.ref = "ui" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "ui" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "ui" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "ui" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "ui" }
junit = { module = "junit:junit", version.ref = "junit" }
material = { module = "com.google.android.material:material", version.ref = "materialVersion" }

[plugins]
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

[bundles]
koin = ["koin-android", "koin-androix-compose"]
base = ["budget-planner-base"]
products = ["budget-planner-onboarding"]
navigations = ["budget-planner-onboarding-navigation"]